/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.controller.InventoryController;
import com.view.inventory.AddInventoryForm;
import com.view.inventory.EditInventoryForm;

import com.controller.DriverController;
import com.view.driver.AddDriverForm;
import com.view.driver.EditDriverForm;

import java.util.HashMap;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author rakakhrl
 */
public class HomeView extends javax.swing.JFrame {
    InventoryController _inventoryCtrl = new InventoryController();
    DriverController _driverCtrl = new DriverController();
    
    String userRole;
    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
        loadTable("all");
    }
    
    private void loadTable(String tablename) {
        switch (tablename) {
            case "inventory":
                inventoryTable.setModel(DbUtils.resultSetToTableModel(_inventoryCtrl.fetchAll()));
                break;
            case "driver":
                driverTable.setModel(DbUtils.resultSetToTableModel(_driverCtrl.fetchAll()));
                break;
            case "transaction":
                // TODO implement fetch transaction table
                break;
            case "all":
                inventoryTable.setModel(DbUtils.resultSetToTableModel(_inventoryCtrl.fetchAll()));
                driverTable.setModel(DbUtils.resultSetToTableModel(_driverCtrl.fetchAll()));
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        transaksiTabBtn = new javax.swing.JButton();
        inventoryTabBtn = new javax.swing.JButton();
        driverTabBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tabView = new javax.swing.JTabbedPane();
        transaksiTab = new javax.swing.JPanel();
        transactionTableScrollPane = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        hapusTransactionBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        transactionSearchTextField = new javax.swing.JTextField();
        searchTransactionBtn = new javax.swing.JButton();
        addTransactionBtn = new javax.swing.JButton();
        changeStatusBtn = new javax.swing.JButton();
        refreshTransactionBtn = new javax.swing.JButton();
        inventoryTab = new javax.swing.JPanel();
        inventoryTableScrollPane = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        hapusBarangBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inventorySearchTextField = new javax.swing.JTextField();
        searchInventoryBtn = new javax.swing.JButton();
        tambahJenisBtn = new javax.swing.JButton();
        editBarangBtn = new javax.swing.JButton();
        refreshInventoryBtn = new javax.swing.JButton();
        driverTab = new javax.swing.JPanel();
        driverTableScrollPane = new javax.swing.JScrollPane();
        driverTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        hapusDriverBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        driverSearchTextField = new javax.swing.JTextField();
        searchDriverBtn = new javax.swing.JButton();
        tambahDriverBtn = new javax.swing.JButton();
        editDriverBtn = new javax.swing.JButton();
        refreshDriverBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 458));

        transaksiTabBtn.setBackground(new java.awt.Color(51, 102, 255));
        transaksiTabBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        transaksiTabBtn.setForeground(new java.awt.Color(255, 255, 255));
        transaksiTabBtn.setText("Transaction");
        transaksiTabBtn.setBorder(null);
        transaksiTabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiTabBtnActionPerformed(evt);
            }
        });

        inventoryTabBtn.setBackground(new java.awt.Color(51, 102, 255));
        inventoryTabBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        inventoryTabBtn.setForeground(new java.awt.Color(255, 255, 255));
        inventoryTabBtn.setText("Inventory");
        inventoryTabBtn.setBorder(null);
        inventoryTabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryTabBtnActionPerformed(evt);
            }
        });

        driverTabBtn.setBackground(new java.awt.Color(51, 102, 255));
        driverTabBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        driverTabBtn.setForeground(new java.awt.Color(255, 255, 255));
        driverTabBtn.setText("Driver");
        driverTabBtn.setBorder(null);
        driverTabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverTabBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transaksiTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inventoryTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
            .addComponent(driverTabBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(transaksiTabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryTabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(driverTabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 561));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 0, 868, 40));
        jPanel4.getAccessibleContext().setAccessibleName("");

        tabView.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        transaksiTab.setBackground(new java.awt.Color(255, 255, 255));
        transaksiTab.setForeground(new java.awt.Color(255, 255, 255));

        transactionTable.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        transactionTableScrollPane.setViewportView(transactionTable);

        jLabel5.setFont(new java.awt.Font("Circular Std Bold", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Transaction Table");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        hapusTransactionBtn.setBackground(new java.awt.Color(255, 0, 51));
        hapusTransactionBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        hapusTransactionBtn.setForeground(new java.awt.Color(255, 255, 255));
        hapusTransactionBtn.setText("Delete");
        hapusTransactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusTransactionBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel6.setLabelFor(inventorySearchTextField);
        jLabel6.setText("Search For Transaction");

        transactionSearchTextField.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        transactionSearchTextField.setPreferredSize(new java.awt.Dimension(59, 25));

        searchTransactionBtn.setBackground(new java.awt.Color(51, 102, 255));
        searchTransactionBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        searchTransactionBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchTransactionBtn.setText("Search");
        searchTransactionBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchTransactionBtn.setPreferredSize(new java.awt.Dimension(73, 25));
        searchTransactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTransactionBtnActionPerformed(evt);
            }
        });

        addTransactionBtn.setBackground(new java.awt.Color(51, 102, 255));
        addTransactionBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        addTransactionBtn.setForeground(new java.awt.Color(255, 255, 255));
        addTransactionBtn.setText("Add");
        addTransactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTransactionBtnActionPerformed(evt);
            }
        });

        changeStatusBtn.setBackground(new java.awt.Color(51, 102, 255));
        changeStatusBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        changeStatusBtn.setForeground(new java.awt.Color(255, 255, 255));
        changeStatusBtn.setText("Change Status");
        changeStatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeStatusBtnActionPerformed(evt);
            }
        });

        refreshTransactionBtn.setBackground(new java.awt.Color(51, 102, 255));
        refreshTransactionBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        refreshTransactionBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshTransactionBtn.setText("Refresh");
        refreshTransactionBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshTransactionBtn.setPreferredSize(new java.awt.Dimension(73, 25));
        refreshTransactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTransactionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transaksiTabLayout = new javax.swing.GroupLayout(transaksiTab);
        transaksiTab.setLayout(transaksiTabLayout);
        transaksiTabLayout.setHorizontalGroup(
            transaksiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transaksiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transactionSearchTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchTransactionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changeStatusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refreshTransactionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, transaksiTabLayout.createSequentialGroup()
                        .addComponent(hapusTransactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addTransactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(transactionTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        transaksiTabLayout.setVerticalGroup(
            transaksiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transaksiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaksiTabLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transactionSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(searchTransactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshTransactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changeStatusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transaksiTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hapusTransactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addTransactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(transactionTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabView.addTab("transaksi", transaksiTab);

        inventoryTab.setBackground(new java.awt.Color(255, 255, 255));

        inventoryTable.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        inventoryTableScrollPane.setViewportView(inventoryTable);

        jLabel1.setFont(new java.awt.Font("Circular Std Bold", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Inventory Table");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        hapusBarangBtn.setBackground(new java.awt.Color(255, 0, 51));
        hapusBarangBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        hapusBarangBtn.setForeground(new java.awt.Color(255, 255, 255));
        hapusBarangBtn.setText("Delete");
        hapusBarangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBarangBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel2.setLabelFor(inventorySearchTextField);
        jLabel2.setText("Search For Inventory");

        inventorySearchTextField.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        inventorySearchTextField.setPreferredSize(new java.awt.Dimension(59, 25));

        searchInventoryBtn.setBackground(new java.awt.Color(51, 102, 255));
        searchInventoryBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        searchInventoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchInventoryBtn.setText("Search");
        searchInventoryBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchInventoryBtn.setPreferredSize(new java.awt.Dimension(73, 25));
        searchInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInventoryBtnActionPerformed(evt);
            }
        });

        tambahJenisBtn.setBackground(new java.awt.Color(51, 102, 255));
        tambahJenisBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        tambahJenisBtn.setForeground(new java.awt.Color(255, 255, 255));
        tambahJenisBtn.setText("Add");
        tambahJenisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahJenisBtnActionPerformed(evt);
            }
        });

        editBarangBtn.setBackground(new java.awt.Color(51, 102, 255));
        editBarangBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        editBarangBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBarangBtn.setText("Edit");
        editBarangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBarangBtnActionPerformed(evt);
            }
        });

        refreshInventoryBtn.setBackground(new java.awt.Color(51, 102, 255));
        refreshInventoryBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        refreshInventoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshInventoryBtn.setText("Refresh");
        refreshInventoryBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshInventoryBtn.setPreferredSize(new java.awt.Dimension(73, 25));
        refreshInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshInventoryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inventoryTabLayout = new javax.swing.GroupLayout(inventoryTab);
        inventoryTab.setLayout(inventoryTabLayout);
        inventoryTabLayout.setHorizontalGroup(
            inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventorySearchTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchInventoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editBarangBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refreshInventoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inventoryTabLayout.createSequentialGroup()
                        .addComponent(hapusBarangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tambahJenisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(inventoryTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        inventoryTabLayout.setVerticalGroup(
            inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventoryTabLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inventorySearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(searchInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editBarangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(inventoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hapusBarangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tambahJenisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(inventoryTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabView.addTab("inventory", inventoryTab);

        driverTab.setBackground(new java.awt.Color(255, 255, 255));

        driverTable.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        driverTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        driverTableScrollPane.setViewportView(driverTable);

        jLabel3.setFont(new java.awt.Font("Circular Std Bold", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Driver Table");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        hapusDriverBtn.setBackground(new java.awt.Color(255, 0, 51));
        hapusDriverBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        hapusDriverBtn.setForeground(new java.awt.Color(255, 255, 255));
        hapusDriverBtn.setText("Delete");
        hapusDriverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusDriverBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel4.setLabelFor(inventorySearchTextField);
        jLabel4.setText("Search For Driver");

        driverSearchTextField.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        driverSearchTextField.setPreferredSize(new java.awt.Dimension(59, 25));

        searchDriverBtn.setBackground(new java.awt.Color(51, 102, 255));
        searchDriverBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        searchDriverBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchDriverBtn.setText("Search");
        searchDriverBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchDriverBtn.setPreferredSize(new java.awt.Dimension(73, 25));
        searchDriverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDriverBtnActionPerformed(evt);
            }
        });

        tambahDriverBtn.setBackground(new java.awt.Color(51, 102, 255));
        tambahDriverBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        tambahDriverBtn.setForeground(new java.awt.Color(255, 255, 255));
        tambahDriverBtn.setText("Add");
        tambahDriverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahDriverBtnActionPerformed(evt);
            }
        });

        editDriverBtn.setBackground(new java.awt.Color(51, 102, 255));
        editDriverBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        editDriverBtn.setForeground(new java.awt.Color(255, 255, 255));
        editDriverBtn.setText("Edit");
        editDriverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDriverBtnActionPerformed(evt);
            }
        });

        refreshDriverBtn.setBackground(new java.awt.Color(51, 102, 255));
        refreshDriverBtn.setFont(new java.awt.Font("Circular Std Bold", 0, 14)); // NOI18N
        refreshDriverBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshDriverBtn.setText("Refresh");
        refreshDriverBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshDriverBtn.setPreferredSize(new java.awt.Dimension(73, 25));
        refreshDriverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshDriverBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout driverTabLayout = new javax.swing.GroupLayout(driverTab);
        driverTab.setLayout(driverTabLayout);
        driverTabLayout.setHorizontalGroup(
            driverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, driverTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(driverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(driverSearchTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchDriverBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editDriverBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refreshDriverBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, driverTabLayout.createSequentialGroup()
                        .addComponent(hapusDriverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tambahDriverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(driverTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        driverTabLayout.setVerticalGroup(
            driverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(driverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverTabLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(driverSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(searchDriverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshDriverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editDriverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(driverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hapusDriverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tambahDriverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(driverTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabView.addTab("driver", driverTab);

        jPanel1.add(tabView, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 11, -1, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void refreshInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshInventoryBtnActionPerformed
        loadTable("inventory");
    }//GEN-LAST:event_refreshInventoryBtnActionPerformed

    private void searchInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInventoryBtnActionPerformed
        String kodeBrg = inventorySearchTextField.getText();
        ResultSet result = _inventoryCtrl.fetchOne(kodeBrg);
        
        inventoryTable.setModel(DbUtils.resultSetToTableModel(result));
    }//GEN-LAST:event_searchInventoryBtnActionPerformed

    private void transaksiTabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiTabBtnActionPerformed
        tabView.setSelectedIndex(0);
    }//GEN-LAST:event_transaksiTabBtnActionPerformed

    private void inventoryTabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryTabBtnActionPerformed
        tabView.setSelectedIndex(1);
    }//GEN-LAST:event_inventoryTabBtnActionPerformed

    private void tambahJenisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahJenisBtnActionPerformed
        AddInventoryForm addInventoryForm = new AddInventoryForm();
        addInventoryForm.setVisible(true);
    }//GEN-LAST:event_tambahJenisBtnActionPerformed

    private void hapusBarangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBarangBtnActionPerformed
        Object kodeBrg = inventoryTable.getValueAt(inventoryTable.getSelectedRow(), 1);
        
        _inventoryCtrl.hapusBarang(kodeBrg.toString());
        loadTable("inventory");
    }//GEN-LAST:event_hapusBarangBtnActionPerformed

    private void editBarangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBarangBtnActionPerformed
        Object selectedKodeBrg = inventoryTable.getValueAt(inventoryTable.getSelectedRow(), 1);
        
        try {
            ResultSet result = _inventoryCtrl.fetchOne(selectedKodeBrg.toString());
            
            if (result.first()) {
                String kodeBrg = result.getString("kode_barang");
                String namaBrg = result.getString("nama_barang");
                float hargaBrg = result.getFloat("harga_perkilo");
                int jumlah = result.getInt("jumlah");
                
                EditInventoryForm editInventoryForm = new EditInventoryForm(kodeBrg, namaBrg, hargaBrg, jumlah);
                editInventoryForm.setVisible(true);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_editBarangBtnActionPerformed

    private void driverTabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverTabBtnActionPerformed
        tabView.setSelectedIndex(2);
    }//GEN-LAST:event_driverTabBtnActionPerformed

    private void hapusDriverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusDriverBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusDriverBtnActionPerformed

    private void searchDriverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDriverBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchDriverBtnActionPerformed

    private void tambahDriverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahDriverBtnActionPerformed
        AddDriverForm addDriverForm = new AddDriverForm();
        
        addDriverForm.setVisible(true);
    }//GEN-LAST:event_tambahDriverBtnActionPerformed

    private void editDriverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDriverBtnActionPerformed
        Object selectedKodeDriver = driverTable.getValueAt(driverTable.getSelectedRow(), 1);
        
        try {
            ResultSet result = _driverCtrl.fetchOne(selectedKodeDriver.toString());
            
            if (result.first()) {
                String kodeDriver = result.getString("kode_driver");
                String namaDriver = result.getString("nama_driver");
                
                EditDriverForm editDriverForm = new EditDriverForm(kodeDriver, namaDriver);
                editDriverForm.setVisible(true);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(HomeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editDriverBtnActionPerformed

    private void refreshDriverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshDriverBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshDriverBtnActionPerformed

    private void hapusTransactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusTransactionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusTransactionBtnActionPerformed

    private void searchTransactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTransactionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTransactionBtnActionPerformed

    private void addTransactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTransactionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTransactionBtnActionPerformed

    private void changeStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeStatusBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeStatusBtnActionPerformed

    private void refreshTransactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTransactionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshTransactionBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTransactionBtn;
    private javax.swing.JButton changeStatusBtn;
    private javax.swing.JTextField driverSearchTextField;
    private javax.swing.JPanel driverTab;
    private javax.swing.JButton driverTabBtn;
    private javax.swing.JTable driverTable;
    private javax.swing.JScrollPane driverTableScrollPane;
    private javax.swing.JButton editBarangBtn;
    private javax.swing.JButton editDriverBtn;
    private javax.swing.JButton hapusBarangBtn;
    private javax.swing.JButton hapusDriverBtn;
    private javax.swing.JButton hapusTransactionBtn;
    private javax.swing.JTextField inventorySearchTextField;
    private javax.swing.JPanel inventoryTab;
    private javax.swing.JButton inventoryTabBtn;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JScrollPane inventoryTableScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton refreshDriverBtn;
    private javax.swing.JButton refreshInventoryBtn;
    private javax.swing.JButton refreshTransactionBtn;
    private javax.swing.JButton searchDriverBtn;
    private javax.swing.JButton searchInventoryBtn;
    private javax.swing.JButton searchTransactionBtn;
    private javax.swing.JTabbedPane tabView;
    private javax.swing.JButton tambahDriverBtn;
    private javax.swing.JButton tambahJenisBtn;
    private javax.swing.JTextField transactionSearchTextField;
    private javax.swing.JTable transactionTable;
    private javax.swing.JScrollPane transactionTableScrollPane;
    private javax.swing.JPanel transaksiTab;
    private javax.swing.JButton transaksiTabBtn;
    // End of variables declaration//GEN-END:variables
}
